# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contacts.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contacts(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(752, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbl_decan = QtWidgets.QLabel(self.centralwidget)
        self.lbl_decan.setGeometry(QtCore.QRect(20, 110, 431, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_decan.setFont(font)
        self.lbl_decan.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 280, 681, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Контакты"))
        self.label_2.setText(_translate("MainWindow", "Ректорат."))
        self.lbl_decan.setText(_translate("MainWindow", "Секретарь - Красивая Милана Леонидовна\n"
"Секретарь - Самохвалова Елена Георгиевна\n"
"Телефон 8 (800) 555-50-50\n"
"E-mail - rektor.sgu@yandex.ru"))
        self.label_4.setText(_translate("MainWindow", "Деканат."))
        self.label_5.setText(_translate("MainWindow", " Декан - Пупкин Василий Эдуардович \n"
"(телефон 8 (800) 000-00-01, E-mail - pupkin.v.sgu@yandex.ru) \n"
"Зам. декана - Прекрасная Василиса Ивановна \n"
"(телефон 8 (800) 000-00-02, E-mail - prekrasnaya.v.sgu@yandex.ru) \n"
"Секретарь - Секретарев Дмитрий Борисович \n"
"(телефон 8 (800) 000-00-03, E-mail - sekretarev.d.sgu@yandex.ru) \n"
"Секретарь - Ухов Евгений Олегович \n"
"(телефон 8 (800) 000-00-04, E-mail - uhov.e.sgu@yandex.ru) \n"
""))
