# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Zap_Step4.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zap_Step4(object):
    def setupUi(self, Zap_Step4):
        Zap_Step4.setObjectName("Zap_Step4")
        Zap_Step4.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Zap_Step4)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setGeometry(QtCore.QRect(510, 180, 171, 51))
        self.btn_load.setObjectName("btn_load")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.edit_number = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_number.setGeometry(QtCore.QRect(340, 130, 341, 20))
        self.edit_number.setMaxLength(5)
        self.edit_number.setObjectName("edit_number")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 120, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(670, 530, 101, 31))
        self.btn_next.setObjectName("btn_next")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 240, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.radio_cash = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_cash.setGeometry(QtCore.QRect(330, 250, 95, 20))
        self.radio_cash.setObjectName("radio_cash")
        self.radio_free = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_free.setGeometry(QtCore.QRect(330, 290, 95, 20))
        self.radio_free.setObjectName("radio_free")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 370, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.radio_copy = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_copy.setGeometry(QtCore.QRect(360, 420, 95, 20))
        self.radio_copy.setObjectName("radio_copy")
        self.radio_orig = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_orig.setGeometry(QtCore.QRect(360, 380, 95, 20))
        self.radio_orig.setObjectName("radio_orig")
        Zap_Step4.setCentralWidget(self.centralwidget)

        self.retranslateUi(Zap_Step4)
        QtCore.QMetaObject.connectSlotsByName(Zap_Step4)

    def retranslateUi(self, Zap_Step4):
        _translate = QtCore.QCoreApplication.translate
        Zap_Step4.setWindowTitle(_translate("Zap_Step4", "MainWindow"))
        self.btn_load.setText(_translate("Zap_Step4", "Загрузить скан"))
        self.label_2.setText(_translate("Zap_Step4", "Сведения об образовании"))
        self.edit_number.setInputMask(_translate("Zap_Step4", "00 00"))
        self.label_5.setText(_translate("Zap_Step4", "Номер аттестата"))
        self.btn_next.setText(_translate("Zap_Step4", "Завершить"))
        self.label.setText(_translate("Zap_Step4", "Заполните анкету"))
        self.label_6.setText(_translate("Zap_Step4", "Форма обучения"))
        self.radio_cash.setText(_translate("Zap_Step4", "Платная"))
        self.radio_free.setText(_translate("Zap_Step4", "Бюджет"))
        self.label_7.setText(_translate("Zap_Step4", "Подаю оригинал/копию"))
        self.radio_copy.setText(_translate("Zap_Step4", "Копия"))
        self.radio_orig.setText(_translate("Zap_Step4", "Оригинал"))
